name: HOWmeet deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Check Node v
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Create env file
        run: |
          echo "VITE_APP_FCM_API_KEY=${{ secrets.VITE_APP_FCM_API_KEY}}" >> .env
          echo "VITE_APP_FCM_AUTH_DOMAIN=${{ secrets.VITE_APP_FCM_AUTH_DOMAIN}}" >> .env
          echo "VITE_APP_FCM_PROJECT_ID=${{ secrets.VITE_APP_FCM_PROJECT_ID}}" >> .env
          echo "VITE_APP_FCM_STORAGE_BUCKET=${{ secrets.VITE_APP_FCM_STORAGE_BUCKET}}" >> .env
          echo "VITE_APP_FCM_MESSAGING_SENDER_ID=${{ secrets.VITE_APP_FCM_MESSAGING_SENDER_ID}}" >> .env
          echo "VITE_APP_FCM_APP_ID=${{ secrets.VITE_APP_FCM_APP_ID}}" >> .env
          echo "VITE_APP_FCM_VAPID_KEY=${{ secrets.VITE_APP_FCM_VAPID_KEY}}" >> .env
          echo "VITE_APP_API_BASE_URL=${{ secrets.VITE_APP_API_BASE_URL}}" >> .env
          echo "VITE_APP_CLIENT_URL=${{ secrets.VITE_APP_CLIENT_URL}}" >> .env
          echo "DEV=${{ secrets.DEV}}" >> .env

      - name: Generate build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 dist s3://howmeet.site

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DEV_AWS_DISTRIBUTION_ID }} --paths "/*"
