name: HOWmeet deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Check Node v
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Generate build
        run: npm run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-northeaset-2 dist s3://howmeet-front

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distributino-id ${{ secrets.DEV_AWS_DISTRIBUTION_ID }}
